FROM python:3.11-slim



ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/booking_project



WORKDIR /app/booking_project



COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt



COPY . .