# Generated by Django 5.0.6 on 2026-02-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtokenmodels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshTokenModels',
        ),
    ]
