events {}

http {
    upstream Users_service {
        server users: 8001
    }

    upstream apartments_service {
        server users: 8001
    }

    upstream Booking_service {
        server users: 8001
    }

    upstream Users_service {
        server users: 8001
    }

    upstream payment_service {
        server users: 8001
    }

    upstream review_service {
        server users: 8001
    }

    server {
    listen 80;

    location /users/ {
        proxy_pass http://users:8001/;
    }

    location /apartments/ {
        proxy_pass http://apartments:8002/;
    }

    location /Bookings/ {
        proxy_pass http://Bookings:8003/;
    }

    location /Payments/ {
        proxy_pass http://Payments:8004/;
    }

    location /reviews/ {
        proxy_pass http://reviews:8005/;
    }
}
}


#1. разобрать что делает данный файл
#1. также какие настройки nginx еще необходимы для проекта в целом
#1.