# Generated by Django 5.0.6 on 2024-09-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_popularapartment'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unavailabledate',
            unique_together={('apartment', 'date')},
        ),
    ]
