# Generated by Django 5.0.6 on 2026-02-02 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_unavailabledate_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unavailabledate',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='when unpaid booking expires', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('session_created', 'Session created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='initiated', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='unavailabledate',
            name='date',
            field=models.DateField(),
        ),
    ]
