# Generated by Django 5.0.6 on 2026-02-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_alter_review_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
