# Generated by Django 5.0.6 on 2026-02-11 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_remove_review_booking'),
        ('booking', '0003_alter_unavailabledate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='booking.booking'),
        ),
    ]
